version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    # Optionally, specify a list of directories to ignore
    # ignore:
    #   - dependency-name
    #   - dependency-name-2
    # Optionally, specify a list of dependencies to group together in a single pull request
    # groups:
    #   spring-boot:
    #     patterns:
    #       - "org.springframework.boot:*"

